### ISSUE TITLE
fix screen casting crashing the phone and fast reboots it

### ISSUE THREAD

**Issue by teh404guy** [Linux4/lineage_OTA#2]
Steps:
1. Have a samsung tv with screencasting
2. Enable screencasting on your phone
3. Click on the settings button underneath in the select casting device screen
4. Go next your tv
5. Connect to it (it might show up duplicates)
6. Accept on tv
7. Phone crashes
Affected models: samsung s10+ exynos

**Comment by Linux4** [comment]
No.
This is not even supposed to work on these devices anymore.
It's mentioned in XDA thread too
Screen casting only works on relatively recent qcom phones since google killed AOSP implementation in Pie.
Anyways it is disabled in latest build to avoid these crashes and instead not even give that option, please update.
